### ISSUE TITLE
More Dragon Eggs

### ISSUE THREAD

**Issue by Fail-2K** [YUNG-GANG/YUNGs-Better-End-Island#13]
Add an option to spawn a dragon egg with each dragon death as More Dragon Eggs does not work with this mod

**Comment by liangmoe** [comment]
is there any solution? ive tried Adventurez and dragonmount, they both have option such as replenishing dragon egg and just not working😭

**Comment by Linguardium** [comment]
the underlying problem is Yung overwrites the method but doesnt use `@Overwrite` meaning it silently causes mods to fail instead of crashing. if it crashed, players would know that yung was breaking a bunch of other mods by replacing methods entirely. 

Since yung is the one completely replacing the methods, it would be up to them to add a compat for the mods they break

**Comment by yungnickyoung** [comment]
The unfortunate thing about vanilla dragon fight code is that it's very bad and difficult to overhaul to the extent I've attempted in this mod. I opted to inject instead of overwrite so that other mod devs can inject with higher priority if they need to, which so far has seemed to be a good choice. That being said, I'll take a look and see if I can get it working properly with this mod.

**Comment by yungnickyoung** [comment]
Added in v2.0.5.
